<a href="https://colab.research.google.com/github/GeorginaLissethJimenezVentura/DATAWAREHOUSE-SEGUROS/blob/main/Clientes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://github.com/GeorginaLissethJimenezVentura/DATAWAREHOUSE-SEGUROS.git

In [1]:
import pandas as pd

In [14]:
url = "https://raw.githubusercontent.com/GeorginaLissethJimenezVentura/DATAWAREHOUSE-SEGUROS/refs/heads/main/data/clientes.csv"

In [15]:
df = pd.read_csv(url)

BLOQUE 2

In [17]:
print("primeras filas del datset")
display(df.head())

primeras filas del datset

,id_cliente,nombre,email,genero,fecha_nacimiento,ciudad,segmento
0,1,José Chávez Pérez,jose.chavez.perez1@gmail.com,Hombre,2011/11/24,SanMiguel,NaN
1,2,Daniela Rojas Ortiz,daniela.rojas.ortiz2@seguro.sv,NaN,01-02-80,Sta. Ana,NaN
2,3,Ricardo Cruz Flores,ricardo.cruz.flores3@example.com,Masculino,06-18-79,S. Miguel,NaN
3,4,María Pérez Pérez,maria.perez.perez4@correo.com,Masculino,1960-09-29,LaLibertad,REGULAR
4,5,Fernanda Chávez Rojas,fernanda.chavez.rojas5@seguro.sv,NaN,1945/08/02,San Salvador,Pyme

In [21]:
print("primeras filas del dataset")
display(df.head())

primeras filas del dataset

,id_cliente,nombre,email,genero,fecha_nacimiento,ciudad,segmento
0,1,José Chávez Pérez,jose.chavez.perez1@gmail.com,Hombre,2011/11/24,SanMiguel,NaN
1,2,Daniela Rojas Ortiz,daniela.rojas.ortiz2@seguro.sv,NaN,01-02-80,Sta. Ana,NaN
2,3,Ricardo Cruz Flores,ricardo.cruz.flores3@example.com,Masculino,06-18-79,S. Miguel,NaN
3,4,María Pérez Pérez,maria.perez.perez4@correo.com,Masculino,1960-09-29,LaLibertad,REGULAR
4,5,Fernanda Chávez Rojas,fernanda.chavez.rojas5@seguro.sv,NaN,1945/08/02,San Salvador,Pyme

In [22]:
print("dimensiones el dataset (filas, columnas)")
print(df.shape)

dimensiones el dataset (filas, columnas)
(3030, 7)

In [19]:
print("valores nulos por columna")
print(df.isnull().sum())

valores nulos por columna
id_cliente            0
nombre                0
email                 0
genero              595
fecha_nacimiento      0
ciudad                0
segmento            597
dtype: int64

In [20]:
print("Registros duplicados")
print(df.duplicated().sum())

Registros duplicados
0

BLOQUE 3: LIMPIEZA DE DATOS

In [27]:
#Elmina espacios al inicio y al final en columnas de texto
for col in df.select_dtypes(include="object").columns:df[col]=df[col].str.strip()

In [28]:
#Normalizar el nombre
df["nombre"]=df["nombre"].str.title()

In [29]:
#Normalizar el mail
df["email"]=df["email"].str.lower()

In [30]:
#Normalizar el genero
df["genero"]=df["genero"].str.upper()

In [37]:
#Convertir fecha de nacimiento a formato fecha
df['fecha_nacimiento']=pd.to_datetime(df['fecha_nacimiento'],errors="coerce")

In [40]:
#Normalizar ciudad
df["ciudad"]=df['ciudad'].str.title()
df['ciudad']=df['ciudad'].astype(str)
df['ciudad']=df['ciudad'].str.strip()
df['ciudad']=df['ciudad'].str.upper()

In [36]:
#Limpieza de nacimiento
df['segmento']=df['segmento'].astype(str)
df['segmento']=df['segmento'].str.strip()
df['segmento']=df['segmento'].str.upper()

In [39]:
for col in df.columns: print(col)

id_cliente
nombre
email
genero
fecha_nacimiento
ciudad
segmento

BLOQUE 4_ VALIDACIÓN DE DATOS

In [43]:
#CREAR COLUMNA PARA REGISTRAR ERRORES
df["motivo_rechazo"] = ""

#validad id_cliente
df.loc[df["id_cliente"].isnull(), "motivo_rechazo"] += "id_cliente nulo; "